export enum MarkerType {
  POOR_LIGHTING = 'POOR_LIGHTING',
  SUSPECTED_DRUG_TRAFFICKING = 'SUSPECTED_DRUG_TRAFFICKING',
  HARASSMENT_REPORTS = 'HARASSMENT_REPORTS',
  UNSAFE_AREA = 'UNSAFE_AREA',
  HIGH_CRIME_RATE = 'HIGH_CRIME_RATE',
  CATCALLING_ZONE = 'CATCALLING_ZONE',
  STALKING_REPORTS = 'STALKING_REPORTS',

  SAFE_SPOT = 'SAFE_SPOT',
  SECURITY_CAMERA = 'SECURITY_CAMERA',
  EMERGENCY_BUTTON = 'EMERGENCY_BUTTON',
  TRUSTED_ESTABLISHMENT = 'TRUSTED_ESTABLISHMENT',

  UNSAFE_BUS_STOP = 'UNSAFE_BUS_STOP',

  NIGHT_DANGER_ZONE = 'NIGHT_DANGER_ZONE',
  WEEKEND_RISK_AREA = 'WEEKEND_RISK_AREA',
}
